#!/bin/bash
# md2asm.sh - Convert markdown directory structure to assembly
# Usage: ./md2asm.sh content_dir > menu_structures.S

CONTENT_DIR="$1"
if [ -z "$CONTENT_DIR" ]; then
    echo "Usage: $0 <content_directory>" >&2
    exit 1
fi

echo "/* AUTO-GENERATED MENU STRUCTURES FROM MARKDOWN */"
echo "/* Generated by md2asm.sh */"
echo ""
echo ".global menu_table"
echo ".global content_table"
echo ""

# Generate content table first
echo ".align 4"
echo "content_table:"
echo "    .long    0    /* Content 0 - unused */"

content_id=1
find "$CONTENT_DIR" -name "*.md" | sort | while read file; do
    title=$(head -n 10 "$file" | grep "^# " | head -n 1 | sed 's/^# //')
    if [ -z "$title" ]; then
        title=$(basename "$file" .md)
    fi
    
    echo "    .long    content_${content_id}_text    /* $title */"
    content_id=$((content_id + 1))
done

echo ""

# Generate content strings
content_id=1
find "$CONTENT_DIR" -name "*.md" | sort | while read file; do
    title=$(head -n 10 "$file" | grep "^# " | head -n 1 | sed 's/^# //')
    if [ -z "$title" ]; then
        title=$(basename "$file" .md)
    fi
    
    echo "content_${content_id}_text:"
    # Escape the content for assembly
    sed 's/\\/\\\\/g; s/"/\\"/g; s/$/\\n/g' "$file" | \
    tr -d '\n' | \
    sed 's/\\n$//g' | \
    sed 's/.*/    .asciz "&"/'
    echo ""
    
    content_id=$((content_id + 1))
done

# Simple menu structure - just list all files as menu items
echo ".align 4"
echo "main_menu_items:"

content_id=1
find "$CONTENT_DIR" -name "*.md" | sort | while read file; do
    title=$(head -n 10 "$file" | grep "^# " | head -n 1 | sed 's/^# //')
    if [ -z "$title" ]; then
        title=$(basename "$file" .md)
    fi
    
    # Create title string
    title_label="title_${content_id}_text"
    echo "${title_label}:"
    echo "    .asciz \"$title\""
    echo "menu_item_${content_id}:"
    echo "    .long    ${title_label}    /* Title */"
    echo "    .long    ${content_id}     /* Content ID */"
    echo ""
    
    content_id=$((content_id + 1))
done

echo "    .long    0, 0    /* End marker */"
echo ""

echo ".align 4"
echo "menu_table:"
echo "    .long    main_menu_def"
echo "    .long    0"
echo ""

echo "main_menu_def:"
echo "    .long    main_menu_title"
echo "    .long    main_menu_items"
echo ""

echo "main_menu_title:"
echo "    .asciz \"JonSharp.net Cyberterminal\"" 