#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>

#define MAX_PATH 512
#define MAX_LINE 2048
#define MAX_CONTENT 65536

typedef struct {
    char title[256];
    char filename[MAX_PATH];
    char content[MAX_CONTENT];
    int content_id;
} content_item_t;

static content_item_t items[256];
static int item_count = 0;

// Escape string for assembly
void escape_for_asm(const char *input, char *output, size_t output_size) {
    const char *src = input;
    char *dst = output;
    char *end = output + output_size - 1;
    
    while (*src && dst < end - 1) {
        switch (*src) {
            case '\\': 
                if (dst < end - 1) { *dst++ = '\\'; *dst++ = '\\'; }
                break;
            case '"':  
                if (dst < end - 1) { *dst++ = '\\'; *dst++ = '"'; }
                break;
            case '\n': 
                if (dst < end - 1) { *dst++ = '\\'; *dst++ = 'n'; }
                break;
            case '\r': 
                // Skip carriage returns
                break;
            default:   
                *dst++ = *src;
                break;
        }
        src++;
    }
    *dst = '\0';
}

// Extract title from markdown content
void extract_title(const char *content, char *title, size_t title_size) {
    const char *line = content;
    
    // Look for first # heading
    while (*line) {
        if (*line == '#' && (line == content || *(line-1) == '\n')) {
            line++; // Skip #
            while (*line == ' ') line++; // Skip spaces
            
            const char *start = line;
            while (*line && *line != '\n') line++;
            
            size_t len = line - start;
            if (len > 0 && len < title_size - 1) {
                strncpy(title, start, len);
                title[len] = '\0';
                // Remove trailing spaces
                while (len > 0 && title[len-1] == ' ') {
                    title[--len] = '\0';
                }
                return;
            }
        }
        
        // Move to next line
        while (*line && *line != '\n') line++;
        if (*line == '\n') line++;
    }
    
    // No title found
    strcpy(title, "Untitled");
}

// Read markdown file
int read_markdown_file(const char *filename, content_item_t *item) {
    FILE *f = fopen(filename, "r");
    if (!f) return 0;
    
    size_t content_pos = 0;
    char line[MAX_LINE];
    
    while (fgets(line, sizeof(line), f) && content_pos < sizeof(item->content) - 1) {
        size_t line_len = strlen(line);
        if (content_pos + line_len < sizeof(item->content) - 1) {
            strcpy(item->content + content_pos, line);
            content_pos += line_len;
        }
    }
    
    fclose(f);
    
    extract_title(item->content, item->title, sizeof(item->title));
    return 1;
}

// Scan directory for markdown files
void scan_directory(const char *dir_path) {
    DIR *dir = opendir(dir_path);
    if (!dir) return;
    
    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL && item_count < 255) {
        if (entry->d_type == DT_REG) {
            // Check if it's a .md file
            size_t name_len = strlen(entry->d_name);
            if (name_len > 3 && strcmp(entry->d_name + name_len - 3, ".md") == 0) {
                char full_path[MAX_PATH];
                snprintf(full_path, sizeof(full_path), "%s/%s", dir_path, entry->d_name);
                
                content_item_t *item = &items[item_count];
                strcpy(item->filename, full_path);
                item->content_id = item_count + 1;
                
                if (read_markdown_file(full_path, item)) {
                    item_count++;
                }
            }
        }
    }
    
    closedir(dir);
}

int main(int argc, char *argv[]) {
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <content_directory>\n", argv[0]);
        return 1;
    }
    
    // Scan for markdown files
    scan_directory(argv[1]);
    
    // Generate assembly output
    printf("/* AUTO-GENERATED FROM MARKDOWN FILES */\n");
    printf("/* Generated by md2asm.c */\n\n");
    
    printf(".global content_table\n");
    printf(".global menu_table\n\n");
    
    // Content table
    printf(".align 4\n");
    printf("content_table:\n");
    printf("    .long    0    /* Content 0 - unused */\n");
    
    for (int i = 0; i < item_count; i++) {
        printf("    .long    content_%d_text    /* %s */\n", 
               items[i].content_id, items[i].title);
    }
    printf("\n");
    
    // Content strings
    for (int i = 0; i < item_count; i++) {
        char escaped[MAX_CONTENT * 2];
        escape_for_asm(items[i].content, escaped, sizeof(escaped));
        
        printf("content_%d_text:\n", items[i].content_id);
        printf("    .asciz \"%s\"\n\n", escaped);
    }
    
    // Menu items
    printf(".align 4\n");
    for (int i = 0; i < item_count; i++) {
        printf("title_%d_text:\n", items[i].content_id);
        printf("    .asciz \"%s\"\n", items[i].title);
        
        printf("menu_item_%d:\n", items[i].content_id);
        printf("    .long    title_%d_text      /* Title pointer at offset 0 */\n", items[i].content_id);
        printf("    .byte    1                   /* Type: 1 = ENTRY_TYPE_TEXT */\n");
        printf("    .byte    0                   /* Padding */\n");
        printf("    .word    %d                  /* Content ID at offset 6 */\n\n", items[i].content_id);
    }
    
    // Menu structure
    printf("main_menu_items:\n");
    for (int i = 0; i < item_count; i++) {
        printf("    .long    menu_item_%d\n", items[i].content_id);
    }
    printf("    .long    0    /* End marker */\n\n");
    
    printf("main_menu_title:\n");
    printf("    .asciz \"JonSharp.net Cyberterminal\"\n\n");
    
    printf("main_menu_def:\n");
    printf("    .long    main_menu_title      /* Title pointer at offset 0 */\n");
    printf("    .word    %d                   /* Item count at offset 4 */\n", item_count);
    printf("    .word    0                    /* Padding to align to long boundary */\n");
    printf("    .long    main_menu_items      /* Item array pointer at offset 8 */\n");
    printf("    .long    0                    /* Content pointer at offset 12 (unused for main menu) */\n\n");
    
    printf(".align 4\n");
    printf("menu_table:\n");
    printf("    .long    main_menu_def\n");
    printf("    .long    0\n");
    
    return 0;
} 