#!/usr/bin/env python3
"""
Menu to ASM Converter

This tool converts YAML menu structure and Markdown content files into
assembly source that can be included in the PCD68 ROM.
"""

import os
import sys
import yaml
import re
import argparse
from pathlib import Path

# Constants
MAX_MENUS = 10
MAX_ITEMS_PER_MENU = 20
MAX_LINE_LENGTH = 80

# Item types - match the constants in pcd68home.S
TYPE_SUBMENU = 0  # ENTRY_TYPE_SUBMENU
TYPE_CONTENT = 1  # ENTRY_TYPE_TEXT (content)
TYPE_LINK = 2     # ENTRY_TYPE_LINK

def parse_frontmatter(content):
    """Parse YAML frontmatter from markdown content"""
    frontmatter = {}
    
    # Check if the content starts with YAML frontmatter
    if content.startswith('---'):
        # Extract frontmatter
        parts = content.split('---', 2)
        if len(parts) >= 3:
            try:
                frontmatter = yaml.safe_load(parts[1])
                content = parts[2].strip()
            except yaml.YAMLError as e:
                print(f"Error parsing frontmatter: {e}")
    
    return frontmatter, content

def sanitize_for_asm(text):
    """Sanitize text for inclusion in assembly strings"""
    # Replace special characters
    text = text.replace('\\', '\\\\')
    text = text.replace('"', '\\"')
    text = text.replace('\n', '\\n')
    text = text.replace('\r', '')
    text = text.replace('\t', '    ')
    
    return text

def sanitize_label(text):
    """Sanitize text for use as an assembly label"""
    # Replace spaces with underscores first
    text = text.replace(' ', '_')
    
    # Replace special characters that aren't valid in assembly labels
    text = re.sub(r'[^a-zA-Z0-9_]', '_', text)
    
    # Ensure label doesn't start with a number
    if text and text[0].isdigit():
        text = 'n' + text
        
    return text

def wrap_text(text, width=76):
    """Wrap text to specified width, preserving words and line breaks"""
    # Split into paragraphs
    paragraphs = text.split('\\n')
    result = []
    
    for paragraph in paragraphs:
        if not paragraph.strip():
            result.append('')
            continue
            
        # Wrap the paragraph
        words = paragraph.split()
        current_line = []
        current_length = 0
        
        for word in words:
            # Check if adding this word would exceed width
            if current_length + len(word) + (1 if current_length > 0 else 0) > width:
                result.append(' '.join(current_line))
                current_line = [word]
                current_length = len(word)
            else:
                if current_length > 0:
                    current_length += 1  # space
                current_line.append(word)
                current_length += len(word)
        
        if current_line:
            result.append(' '.join(current_line))
            
    return '\\n'.join(result)

def content_to_asm(md_file, content_id):
    """Convert markdown content to assembly string declarations"""
    try:
        with open(md_file, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading markdown file {md_file}: {e}")
        return f"content_{content_id}_text:\n    .asciz \"Error loading content\"\n"
    
    # Parse frontmatter and content
    frontmatter, content_text = parse_frontmatter(content)
    
    # Process content for assembly
    content_lines = []
    
    # Extract title from frontmatter or first heading
    title = frontmatter.get('title', '')
    if not title:
        # Try to get title from first heading
        heading_match = re.search(r'^#\s+(.+)$', content_text, re.MULTILINE)
        if heading_match:
            title = heading_match.group(1).strip()
    
    # Sanitize content for assembly
    content_text = sanitize_for_asm(content_text)
    
    # Generate the assembly
    safe_id = sanitize_label(f"content_{content_id}")
    asm_content = [f"{safe_id}_text:"]
    
    # For multi-line strings, use a simple format with a single .asciz directive
    asm_content.append(f'    .asciz "{content_text}"')
    
    return '\n'.join(asm_content)

def generate_menu_structures(menu_data, content_dir):
    """Generate assembly code for menu structures"""
    menus = {}
    content_items = {}
    content_id_counter = 0
    menu_items_asm = []
    menu_defs_asm = []
    content_text_asm = []
    content_files = {}  # Track content files and their IDs
    title_strings = []  # Track all title strings
    
    # Initialize the structure
    asm_output = [
        "/* AUTO-GENERATED MENU STRUCTURES",
        " * Generated by menu2asm.py",
        " * DO NOT EDIT DIRECTLY",
        " */",
        "",
        "/* Export global symbols as weak to avoid conflicts */",
        ".weak menu_table",
        ".weak content_text_ptrs",
        ".weak get_content_pointer",
        ""
    ]
    
    # First pass: collect all menus and assign IDs
    menu_ids = {}
    for menu_id, menu in menu_data.items():
        menu_ids[menu_id] = len(menu_ids)
    
    # Second pass: process menu items and content
    all_titles = set()  # Collect all titles for string generation
    
    for menu_id, menu in menu_data.items():
        menu_index = menu_ids[menu_id]
        title = menu.get('title', menu_id.replace('_', ' ').title())
        key_prefix = menu.get('key_prefix', '')
        parent_id = menu.get('parent', '')
        parent_index = menu_ids.get(parent_id, -1)
        
        # Add menu title to title collection
        all_titles.add(title)
        
        # Sanitize the menu_id for assembly
        safe_menu_id = sanitize_label(menu_id)
        
        # Process items
        items = menu.get('items', [])
        item_ids = []
        
        for item in sorted(items, key=lambda x: x.get('order', 999)):
            item_id = item.get('id', '')
            item_title = item.get('title', item_id.replace('_', ' ').title())
            item_key = item.get('key', '')
            item_type = TYPE_SUBMENU if item.get('type') == 'submenu' else TYPE_CONTENT
            
            # Add item title to title collection
            all_titles.add(item_title)
            
            # Sanitize the item_id for assembly
            safe_item_id = sanitize_label(item_id)
            
            # Handle content files
            content_file = item.get('content_file', '')
            target_index = 0
            
            if item_type == TYPE_SUBMENU:
                if item_id in menu_ids:
                    target_index = menu_ids[item_id]
            elif content_file:
                # Process content file
                md_path = os.path.join(content_dir, content_file)
                if os.path.exists(md_path):
                    content_id = content_id_counter
                    if content_file not in content_files:
                        content_files[content_file] = content_id
                        content_text_asm.append(content_to_asm(md_path, content_id))
                        content_id_counter += 1
                    else:
                        content_id = content_files[content_file]
                    target_index = content_id
                else:
                    print(f"Warning: Content file {content_file} not found")
            
            # Create menu item structure
            item_ids.append({
                'id': safe_item_id,
                'title': item_title,
                'key': item_key,
                'type': item_type,
                'target_index': target_index
            })
        
        menus[menu_id] = {
            'index': menu_index,
            'title': title,
            'items': item_ids,
            'parent': parent_index
        }
    
    # Generate title strings first
    for title in all_titles:
        sanitized_content = sanitize_for_asm(title)
        safe_label = sanitize_label(title)
        asm_id = f"{safe_label}_text"
        title_strings.append(f"{asm_id}:")
        title_strings.append(f"    .asciz    \"{sanitized_content}\"")
        title_strings.append("")
    
    # Generate menu structures with correct format
    for menu_id, menu in menu_data.items():
        safe_menu_id = sanitize_label(menu_id)
        menu_info = menus[menu_id]
        title = menu_info['title']
        items = menu_info['items']
        
        # Create menu item array (pointers to item structures)
        array_name = f"{safe_menu_id}_items_array"
        menu_items_asm.append(f"{array_name}:")
        for i, item in enumerate(items):
            safe_item_id = sanitize_label(item['id'])
            item_asm_id = f"{safe_menu_id}_{safe_item_id}_item"
            menu_items_asm.append(f"    .long    {item_asm_id}")
        menu_items_asm.append(f"    .long    0    /* End of items */")
        menu_items_asm.append("")
        
        # Create individual item structures
        for i, item in enumerate(items):
            safe_item_id = sanitize_label(item['id'])
            item_asm_id = f"{safe_menu_id}_{safe_item_id}_item"
            item_title = item['title']
            safe_title = sanitize_label(item_title)
            
            menu_items_asm.append(f"{item_asm_id}:")
            menu_items_asm.append(f"    .long    {safe_title}_text    /* Title pointer */")
            menu_items_asm.append(f"    .byte    {item['type']}          /* Type: {0 if item['type'] == TYPE_SUBMENU else 1} = {'submenu' if item['type'] == TYPE_SUBMENU else 'content'} */")
            menu_items_asm.append(f"    .byte    0                    /* Padding */")
            menu_items_asm.append(f"    .word    {item['target_index']}       /* {'Target menu' if item['type'] == TYPE_SUBMENU else 'Content ID'} */")
            menu_items_asm.append("")
        
        # Create menu definition
        safe_title = sanitize_label(title)
        menu_defs_asm.append(f"{safe_menu_id}_def:")
        menu_defs_asm.append(f"    .long    {safe_title}_text    /* Title pointer */")
        menu_defs_asm.append(f"    .word    {len(items)}   /* Item count */")
        menu_defs_asm.append(f"    .word    0               /* Padding */")
        menu_defs_asm.append(f"    .long    {array_name}    /* Item array pointer */")
        menu_defs_asm.append("")
    
    # Build the main menu table
    menu_table = ["/* Menu table */",
                  "/* Define menu table - each entry is a pointer to a menu definition */",
                  ".global menu_table",
                  "menu_table:"]
    
    for menu_id in sorted(menu_data.keys(), key=lambda k: menu_ids[k]):
        menu_index = menu_ids[menu_id]
        safe_menu_id = sanitize_label(menu_id)
        menu_title = menu_data[menu_id].get('title', menu_id.replace('_', ' ').title())
        menu_table.append(f"    .long    {safe_menu_id}_def    /* Menu ID {menu_index} - {menu_title} */")
    
    # Pad to MAX_MENUS
    for i in range(len(menu_ids), MAX_MENUS):
        menu_table.append("    .long   0")
    menu_table.append("")
    
    # Create content_text_ptrs table
    if content_text_asm:
        asm_output.append(".global content_text_ptrs")
        asm_output.append("content_text_ptrs:")
        
        # Initialize all entries to 0 for the 10x16 matrix
        for menu_index in range(10):  # Up to 10 menus
            content_entries = []
            for item_index in range(16):  # Each menu gets 16 slots
                # Look up content ID from the map
                content_pointer = "0"
                
                # Replace 0 with actual content pointer for entries that have content
                menu_ids_list = list(menu_ids.keys())
                if menu_index < len(menu_ids_list):
                    menu_id = menu_ids_list[menu_index]
                    menu = menu_data.get(menu_id, {})
                    items = menu.get('items', [])
                    sorted_items = sorted(items, key=lambda x: x.get('order', 999))
                    
                    if item_index < len(sorted_items):
                        item = sorted_items[item_index]
                        if item.get('type') == 'content':
                            content_file = item.get('content_file', '')
                            if content_file and content_file in content_files:
                                content_id = content_files[content_file]
                                content_pointer = f"content_{content_id}_text"
                
                content_entries.append(f"    .long    {content_pointer}")
            asm_output.append(f"    /* Menu {menu_index} content */")
            asm_output.extend(content_entries)
        
        asm_output.append("")
    
    # Combine all parts
    asm_output.extend([
        "/* String literals for all titles */",
        *title_strings,
        "/* Menu item definitions */",
        *menu_items_asm,
        "/* Menu definitions */",
        *menu_defs_asm,
        "/* Menu table */", 
        *menu_table
    ])
    
    # Add content text definitions
    if content_text_asm:
        asm_output.append("/* Content text strings */")
        asm_output.extend(content_text_asm)
    
    # Add the get_content_pointer function implementation
    if content_text_asm:
        asm_output.append("")
        asm_output.append("/* Get content pointer based on menu ID and selection */")
        asm_output.append(".align 2")
        asm_output.append("get_content_pointer:")
        asm_output.append("    /* Input: D0 = menu ID, D1 = selection */")
        asm_output.append("    /* Output: A0 = content pointer */")
        asm_output.append("    /* Check if menu ID is valid */")
        asm_output.append("    cmpw    #0, %d0")
        asm_output.append("    blt     content_error    /* Invalid menu ID */")
        asm_output.append("    cmpw    #4, %d0")
        asm_output.append("    bgt     content_error    /* Invalid menu ID */")
        asm_output.append("")
        asm_output.append("    /* Calculate index into content_text_ptrs table */")
        asm_output.append("    /* Menu ID * 16 + item index = array index */")
        asm_output.append("    lslw    #4, %d0         /* Multiply menu ID by 16 */")
        asm_output.append("    addw    %d1, %d0        /* Add item index */")
        asm_output.append("    ")
        asm_output.append("    /* Get content text pointer */")
        asm_output.append("    lslw    #2, %d0         /* Multiply by 4 for long word offset */")
        asm_output.append("    lea     content_text_ptrs, %a0")
        asm_output.append("    addl    %d0, %a0")
        asm_output.append("    movel   (%a0), %a0")
        asm_output.append("    rts")
        asm_output.append("    ")
        asm_output.append(".align 2")
        asm_output.append("content_error:")
        asm_output.append("    /* Return a pointer to an error message */")
        asm_output.append("    lea     content_error_text, %a0")
        asm_output.append("    rts")
        asm_output.append("")
        asm_output.append("content_error_text:")
        asm_output.append("    .asciz \"Error: Content not found\"")
    
    asm_output.append("")
    
    return '\n'.join(asm_output)

def main():
    parser = argparse.ArgumentParser(description='Convert menu YAML and Markdown content to assembly')
    parser.add_argument('menu_file', help='YAML file containing menu structure')
    parser.add_argument('content_dir', help='Directory containing content files')
    parser.add_argument('--output-dir', default='.', help='Directory to output assembly files')
    args = parser.parse_args()

    # Create output directory if it doesn't exist
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)
    
    # Process menu structure
    with open(args.menu_file, 'r') as f:
        menu_data = yaml.safe_load(f)
    
    # Generate menu structures
    asm_output = generate_menu_structures(menu_data, args.content_dir)
    
    # Save to file
    menu_structures_file = os.path.join(args.output_dir, 'menu_structures.S')
    with open(menu_structures_file, 'w') as f:
        f.write(asm_output)
    print(f"Generated menu structures in {menu_structures_file}")

if __name__ == "__main__":
    main() 