// Tool to generate a compile-time const exec table for Moira
// This extracts the logic from createJumpTables() and generates a C++ source file
// with a const array that can be placed in flash memory

#include <iostream>
#include <fstream>
#include <iomanip>
#include <vector>
#include <map>

// These correspond to Moira's internal enums
enum Instr {
    ILLEGAL, ANDICCR, ANDISR, MOVE, MOVEA, MOVEQ, MOVEM, MOVEP,
    LEA, PEA, CLR, EXT, EXTB, TST, NBCD, TAS, MUL, DIV,
    ADD, ADDA, ADDI, ADDQ, ADDX, SUB, SUBA, SUBI, SUBQ, SUBX,
    CMP, CMPA, CMPI, CMPM, EOR, EORI, EORICCR, EORISR,
    AND, ANDI, OR, ORI, ORICCR, ORISR, NOT, NEG, NEGX,
    LSL, LSR, ASL, ASR, ROL, ROR, ROXL, ROXR,
    SWAP, EXG, SCC, BCC, BRA, BSR, JMP, JSR, DBCC, TRAP, TRAPV,
    RTE, RTR, RTS, NOP, RESET, STOP, CHK, LINK, UNLK,
    BTST, BCHG, BCLR, BSET, SBCD, ABCD, RTD, TCC, BKPT, MOVEC, MOVES
};

enum Mode {
    MODE_DN, MODE_AN, MODE_AI, MODE_PI, MODE_PD, MODE_DI, MODE_IX,
    MODE_AW, MODE_AL, MODE_DIPC, MODE_IXPC, MODE_IM, MODE_IP
};

enum Size {
    Byte = 1, Word = 2, Long = 4
};

struct InstrInfo {
    const char* mnemonic;
    Instr instr;
    Mode mode;
    Size size;
    const char* exec_func;
};

// This table maps opcodes to their corresponding exec functions
// Based on Moira's createJumpTables logic
static std::vector<InstrInfo> generateOpcodeMap() {
    std::vector<InstrInfo> opcodes;

    // Initialize all 65536 entries to execIllegal
    for (int i = 0; i < 65536; i++) {
        opcodes.push_back({"ILLEGAL", ILLEGAL, MODE_IP, Byte, "&Moira::execIllegal"});
    }

    // Now fill in the actual instructions
    // This is a simplified version - in reality we'd need to port all of createJumpTables

    // MOVE.B (0x1xxx)
    for (int op = 0x1000; op < 0x2000; op++) {
        int src = (op >> 3) & 0x3F;
        int dst = ((op >> 6) & 0x3F);

        // Simplified - would need full addressing mode decoding
        if ((op & 0xF000) == 0x1000) {
            opcodes[op] = {"MOVE.B", MOVE, MODE_DN, Byte, "&Moira::execMove0<MOVE, MODE_DN, Byte>"};
        }
    }

    // MOVE.W (0x3xxx)
    for (int op = 0x3000; op < 0x4000; op++) {
        opcodes[op] = {"MOVE.W", MOVE, MODE_DN, Word, "&Moira::execMove0<MOVE, MODE_DN, Word>"};
    }

    // JMP (0x4EF9)
    opcodes[0x4EF9] = {"JMP", JMP, MODE_AL, Long, "&Moira::execJmp<JMP, MODE_AL, Long>"};

    // JSR (0x4EB9)
    opcodes[0x4EB9] = {"JSR", JSR, MODE_AL, Long, "&Moira::execJsr<JSR, MODE_AL, Long>"};

    // MOVEQ (0x7xxx)
    for (int op = 0x7000; op < 0x8000; op += 2) {
        if ((op & 0xF100) == 0x7000) {
            opcodes[op] = {"MOVEQ", MOVEQ, MODE_DN, Long, "&Moira::execMoveq<MOVEQ, MODE_DN, Long>"};
        }
    }

    return opcodes;
}

int main() {
    std::cout << "Generating Moira exec table for flash..." << std::endl;

    auto opcodes = generateOpcodeMap();

    std::ofstream out("MoiraExecTable.cpp");

    out << "// Auto-generated Moira exec table for flash memory\n";
    out << "// This file is generated by generate_exec_table.cpp\n\n";
    out << "#include \"Moira.h\"\n\n";
    out << "namespace moira {\n\n";
    out << "#if USE_EXEC_TABLE_IN_FLASH\n\n";

    // Generate the const exec table
    out << "// Const exec table placed in flash memory\n";
    out << "const Moira::ExecPtr Moira::exec_flash[65536] = {\n";

    for (size_t i = 0; i < opcodes.size(); i++) {
        if (i % 8 == 0) out << "    ";
        out << opcodes[i].exec_func;
        if (i < opcodes.size() - 1) out << ",";
        if ((i + 1) % 8 == 0) out << "\n";
        else if (i < opcodes.size() - 1) out << " ";
    }

    out << "\n};\n\n";
    out << "#endif // USE_EXEC_TABLE_IN_FLASH\n\n";
    out << "} // namespace moira\n";

    std::cout << "Generated MoiraExecTable.cpp" << std::endl;
    return 0;
}