/* 
 * Generated Cyberterminal Content
 * DO NOT EDIT - This file is automatically generated by md2c.sh
 */

#ifndef CYBERTERMINAL_CONTENT_H
#define CYBERTERMINAL_CONTENT_H

/* Content item structure */
typedef struct {
    const char* title;
    const char* type;
    int order;
    const char* content;
} ContentItem;

/* Menu item structure */
typedef struct {
    const char* title;
    const char* type;
    int order;
    int target_id;
} MenuItem;

/* Menu structure */
typedef struct {
    int id;
    int parent_id;
    const char* title;
    const char* content;
    int item_count;
    MenuItem items[20]; /* Max 20 items per menu */
} Menu;

/* Placeholder data - will be replaced by generated content */
#define CONTENT_ITEM_COUNT 5
const ContentItem content_items[CONTENT_ITEM_COUNT] = {
    { "Bio", "content", 1, "About Jon Sharp\n\nJon Sharp is a software engineer and hardware enthusiast with a passion for retro computing, embedded systems, and open source development." },
    { "Skills & Interests", "content", 2, "Skills & Interests\n\n- 68000 Assembly Programming\n- Embedded System Design\n- C/C++ Development\n- Hardware Prototyping\n- Retrocomputing" },
    { "PCD-68 Computer", "content", 1, "PCD-68 Computer\n\nThe PCD-68 is a Motorola 68000-based virtual retro computer emulator." },
    { "Bare-metal Macintosh Programming", "content", 2, "Bare-metal Macintosh Programming\n\nI've been tinkering with 68000 assembly off and on over the past decade." },
    { "Contact Information", "content", 1, "Contact Information\n\nJon Sharp can be reached through various channels." }
};

#define MENU_COUNT 3
#define ROOT_MENU_ID 0
const Menu menus[MENU_COUNT] = {
    {
        0, /* menu_id */
        -1, /* parent_id */
        "Main Menu", /* title */
        "Welcome to the JonSharp.net cyberterminal.", /* content */
        3, /* item_count */
        { /* items */
            { "About Jon Sharp", "submenu", 1, 1 },
            { "Projects", "submenu", 2, 2 },
            { "Contact Information", "content", 5, 4 }
        }
    },
    {
        1, /* menu_id */
        0, /* parent_id */
        "About Jon Sharp", /* title */
        "Information about Jon Sharp, including his background, skills, and experience.", /* content */
        2, /* item_count */
        { /* items */
            { "Bio", "content", 1, 0 },
            { "Skills & Interests", "content", 2, 1 }
        }
    },
    {
        2, /* menu_id */
        0, /* parent_id */
        "Projects", /* title */
        "Various hardware and software projects by Jon Sharp.", /* content */
        2, /* item_count */
        { /* items */
            { "PCD-68 Computer", "content", 1, 2 },
            { "Bare-metal Macintosh Programming", "content", 2, 3 }
        }
    }
};

#endif /* CYBERTERMINAL_CONTENT_H */